"""create property management tables

Revision ID: 2b3d8a418bb6
Revises: f3d776fa1bc0
Create Date: 2026-08-03 17:55:06.230634+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from uuid6 import uuid7


revision: str = '2b3d8a418bb6'
down_revision: str | None = 'f3d776fa1bc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_types')),
    sa.UniqueConstraint('name', name=op.f('uq_property_types_name'))
    )
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_properties_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], name=op.f('fk_properties_property_type_id_property_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_table('unit_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_adults', sa.SmallInteger(), nullable=False),
    sa.Column('max_children', sa.SmallInteger(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_unit_types_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_unit_types_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_types')),
    sa.UniqueConstraint('property_id', 'name', name=op.f('uq_unit_types_property_id'))
    )
    op.create_index(op.f('ix_unit_types_organization_id'), 'unit_types', ['organization_id'], unique=False)
    op.create_index(op.f('ix_unit_types_property_id'), 'unit_types', ['property_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('available', 'maintenance', 'out_of_service', name='unit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_units_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_units_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], name=op.f('fk_units_unit_type_id_unit_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('property_id', 'code', name=op.f('uq_units_property_id'))
    )
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_index(op.f('ix_units_unit_type_id'), 'units', ['unit_type_id'], unique=False)

    # Seed the global property-type catalog.
    property_types = sa.table(
        'property_types',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('description', sa.Text()),
    )
    op.bulk_insert(
        property_types,
        [
            {'id': str(uuid7()), 'name': name, 'description': description}
            for name, description in [
                ('HOTEL', 'Multi-room property with front desk operations'),
                ('RESORT', 'Multi-building property with amenities and activities'),
                ('VILLA', 'Whole-unit rental, often with private facilities'),
                ('CABANA', 'Small standalone unit, typically seasonal'),
                ('HOSTEL', 'Bed-level inventory with shared dorms'),
                ('GUEST_HOUSE', 'Small owner-operated property'),
                ('APARTMENT', 'Unit-level inventory for short or long stays'),
                ('OTHER', 'Any property type not covered above'),
            ]
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_type_id'), table_name='units')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_unit_types_property_id'), table_name='unit_types')
    op.drop_index(op.f('ix_unit_types_organization_id'), table_name='unit_types')
    op.drop_table('unit_types')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('property_types')
    sa.Enum(name='unit_status').drop(op.get_bind())
    # ### end Alembic commands ###
