"""create availability and pricing tables

Revision ID: 7956b07ae086
Revises: c928e834651b
Create Date: 2026-08-03 18:10:09.438620+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7956b07ae086'
down_revision: str | None = 'c928e834651b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rule_type', sa.Enum('seasonal', 'weekend', 'holiday', 'special', name='pricing_rule_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NOT NULL OR percentage IS NOT NULL', name=op.f('ck_pricing_rules_ck_pricing_rules_has_adjustment')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_pricing_rules_ck_pricing_rules_date_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pricing_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_pricing_rules_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], name=op.f('fk_pricing_rules_unit_type_id_unit_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index(op.f('ix_pricing_rules_organization_id'), 'pricing_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_property_id'), 'pricing_rules', ['property_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_unit_type_id'), 'pricing_rules', ['unit_type_id'], unique=False)
    op.create_table('unit_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('available', 'blocked', 'maintenance', name='availability_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_unit_availability_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_unit_availability_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_unit_availability_unit_id_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_availability')),
    sa.UniqueConstraint('unit_id', 'date', name='uq_unit_availability_unit_id_date')
    )
    op.create_index(op.f('ix_unit_availability_date'), 'unit_availability', ['date'], unique=False)
    op.create_index(op.f('ix_unit_availability_organization_id'), 'unit_availability', ['organization_id'], unique=False)
    op.create_index(op.f('ix_unit_availability_property_id'), 'unit_availability', ['property_id'], unique=False)
    op.create_index(op.f('ix_unit_availability_unit_id'), 'unit_availability', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_availability_unit_id'), table_name='unit_availability')
    op.drop_index(op.f('ix_unit_availability_property_id'), table_name='unit_availability')
    op.drop_index(op.f('ix_unit_availability_organization_id'), table_name='unit_availability')
    op.drop_index(op.f('ix_unit_availability_date'), table_name='unit_availability')
    op.drop_table('unit_availability')
    op.drop_index(op.f('ix_pricing_rules_unit_type_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_property_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_organization_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    sa.Enum(name='availability_status').drop(op.get_bind())
    sa.Enum(name='pricing_rule_type').drop(op.get_bind())
    # ### end Alembic commands ###
