"""create billing tables

Revision ID: e458f94ad144
Revises: 7956b07ae086
Create Date: 2026-08-03 18:14:46.780620+00:00
"""
from collections.abc import Sequence
from datetime import date, timedelta

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid6 import uuid7


revision: str = 'e458f94ad144'
down_revision: str | None = '7956b07ae086'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_properties', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_plans_name'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'cancelled', 'expired', name='subscription_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'void', name='invoice_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_invoices_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)

    # At most one live (trial/active) subscription per organization.
    op.create_index(
        'uq_subscriptions_one_live_per_org',
        'subscriptions',
        ['organization_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('trial', 'active')"),
    )

    plans = sa.table(
        'plans',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('price_monthly', sa.Numeric()),
        sa.column('price_yearly', sa.Numeric()),
        sa.column('max_properties', sa.Integer()),
        sa.column('max_users', sa.Integer()),
        sa.column('features', postgresql.JSONB()),
        sa.column('is_active', sa.Boolean()),
    )

    free_id = str(uuid7())
    starter_id = str(uuid7())
    professional_id = str(uuid7())
    enterprise_id = str(uuid7())

    op.bulk_insert(
        plans,
        [
            {
                'id': free_id,
                'name': 'FREE',
                'description': 'Trial plan for evaluating Lodgwise AI',
                'price_monthly': 0,
                'price_yearly': 0,
                'max_properties': 1,
                'max_users': 2,
                'features': {
                    'bookings': True,
                    'availability': True,
                    'ai_assistant': False,
                    'channel_manager': False,
                },
                'is_active': True,
            },
            {
                'id': starter_id,
                'name': 'STARTER',
                'description': 'For single-property operators',
                'price_monthly': 29,
                'price_yearly': 290,
                'max_properties': 3,
                'max_users': 5,
                'features': {
                    'bookings': True,
                    'availability': True,
                    'ai_assistant': False,
                    'channel_manager': False,
                },
                'is_active': True,
            },
            {
                'id': professional_id,
                'name': 'PROFESSIONAL',
                'description': 'For growing multi-property businesses',
                'price_monthly': 99,
                'price_yearly': 990,
                'max_properties': 15,
                'max_users': 25,
                'features': {
                    'bookings': True,
                    'availability': True,
                    'ai_assistant': True,
                    'channel_manager': True,
                },
                'is_active': True,
            },
            {
                'id': enterprise_id,
                'name': 'ENTERPRISE',
                'description': 'Unlimited scale with advanced controls',
                'price_monthly': 299,
                'price_yearly': 2990,
                'max_properties': 1000,
                'max_users': 500,
                'features': {
                    'bookings': True,
                    'availability': True,
                    'ai_assistant': True,
                    'channel_manager': True,
                    'sso': True,
                    'dedicated_support': True,
                },
                'is_active': True,
            },
        ],
    )

    # Backfill a FREE trial for every existing organization.
    conn = op.get_bind()
    org_ids = conn.execute(sa.text('SELECT id FROM organizations')).fetchall()
    if org_ids:
        today = date.today()
        end = today + timedelta(days=14)
        subscriptions = sa.table(
            'subscriptions',
            sa.column('id', sa.UUID()),
            sa.column('organization_id', sa.UUID()),
            sa.column('plan_id', sa.UUID()),
            sa.column('status', sa.Enum(name='subscription_status')),
            sa.column('start_date', sa.Date()),
            sa.column('end_date', sa.Date()),
            sa.column('next_billing_date', sa.Date()),
        )
        op.bulk_insert(
            subscriptions,
            [
                {
                    'id': str(uuid7()),
                    'organization_id': str(row[0]),
                    'plan_id': free_id,
                    'status': 'trial',
                    'start_date': today,
                    'end_date': end,
                    'next_billing_date': None,
                }
                for row in org_ids
            ],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_subscriptions_one_live_per_org', table_name='subscriptions')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    sa.Enum(name='subscription_status').drop(op.get_bind())
    sa.Enum(name='invoice_status').drop(op.get_bind())
    # ### end Alembic commands ###
